export const postcardTemplates = [
  {
    id: 'realtor-listing',
    name: 'Just Sold - Real Estate',
    category: 'Real Estate',
    size: '4x6',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-1',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: '#0F172A',
          locked: true,
        },
        {
          id: 'accent-bar',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 600,
          height: 60,
          fill: '#3B82F6',
          locked: false,
        },
        {
          id: 'title-1',
          type: 'text',
          x: 40,
          y: 15,
          text: 'JUST SOLD!',
          fontSize: 32,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#FFFFFF',
          locked: false,
        },
        {
          id: 'headline-1',
          type: 'text',
          x: 40,
          y: 100,
          text: 'Your Neighbor\'s Home',
          fontSize: 36,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#FFFFFF',
          locked: false,
        },
        {
          id: 'subtitle-1',
          type: 'text',
          x: 40,
          y: 150,
          text: 'Recently Sold for Top Dollar',
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#94A3B8',
          locked: false,
        },
        {
          id: 'cta-1',
          type: 'text',
          x: 40,
          y: 330,
          text: 'Wondering what YOUR home is worth?',
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: '600',
          fill: '#3B82F6',
          locked: false,
        },
      ],
    },
  },
  {
    id: 'market-update',
    name: 'Market Update - Neighborhood',
    category: 'Real Estate',
    size: '6x9',
    thumbnail: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-2',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: '#F8FAFC',
          locked: true,
        },
        {
          id: 'header-bar',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 900,
          height: 120,
          fill: '#10B981',
          locked: false,
        },
        {
          id: 'title-2',
          type: 'text',
          x: 60,
          y: 35,
          text: 'YOUR NEIGHBORHOOD',
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#FFFFFF',
          locked: false,
        },
        {
          id: 'subtitle-2',
          type: 'text',
          x: 60,
          y: 70,
          text: 'Market Update - January 2026',
          fontSize: 18,
          fontFamily: 'Inter',
          fill: '#D1FAE5',
          locked: false,
        },
        {
          id: 'stat-label-1',
          type: 'text',
          x: 60,
          y: 180,
          text: 'MEDIAN HOME PRICE',
          fontSize: 14,
          fontFamily: 'Inter',
          fontWeight: '600',
          fill: '#64748B',
          locked: false,
        },
        {
          id: 'stat-value-1',
          type: 'text',
          x: 60,
          y: 210,
          text: '$425,000',
          fontSize: 48,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#0F172A',
          locked: false,
        },
        {
          id: 'body-text',
          type: 'text',
          x: 60,
          y: 450,
          text: 'Home values are up. Now is the perfect time to sell!',
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#334155',
          locked: false,
        },
      ],
    },
  },
  {
    id: 'open-house',
    name: 'Open House Invitation',
    category: 'Real Estate',
    size: '4x6',
    thumbnail: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-3',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: '#FFFFFF',
          locked: true,
        },
        {
          id: 'top-accent',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 600,
          height: 8,
          fill: '#10B981',
          locked: false,
        },
        {
          id: 'title-3',
          type: 'text',
          x: 50,
          y: 40,
          text: 'OPEN HOUSE',
          fontSize: 42,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#0F172A',
          locked: false,
        },
        {
          id: 'date-3',
          type: 'text',
          x: 50,
          y: 100,
          text: 'Saturday & Sunday',
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#10B981',
          locked: false,
        },
        {
          id: 'time-3',
          type: 'text',
          x: 50,
          y: 135,
          text: '1:00 PM - 4:00 PM',
          fontSize: 20,
          fontFamily: 'Inter',
          fontWeight: '600',
          fill: '#64748B',
          locked: false,
        },
        {
          id: 'address-3',
          type: 'text',
          x: 50,
          y: 200,
          text: '{{address_line1}}',
          fontSize: 22,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#0F172A',
          locked: false,
        },
        {
          id: 'features',
          type: 'text',
          x: 50,
          y: 250,
          text: '4 Bed • 3 Bath • 2,400 Sq Ft • Pool',
          fontSize: 16,
          fontFamily: 'Inter',
          fill: '#64748B',
          locked: false,
        },
        {
          id: 'cta-3',
          type: 'text',
          x: 50,
          y: 330,
          text: 'See you there!',
          fontSize: 18,
          fontFamily: 'Inter',
          fontStyle: 'italic',
          fill: '#10B981',
          locked: false,
        },
      ],
    },
  },
  {
    id: 'blank-modern',
    name: 'Modern Blank Canvas',
    category: 'Blank',
    size: '4x6',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-4',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 600,
          height: 400,
          fill: '#FFFFFF',
          locked: true,
        },
      ],
    },
  },
  {
    id: 'seasonal-spring',
    name: 'Spring Sale Promo',
    category: 'Seasonal',
    size: '6x9',
    thumbnail: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-5',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 900,
          height: 600,
          fill: '#FEF3C7',
          locked: true,
        },
        {
          id: 'circle-accent',
          type: 'circle',
          x: 700,
          y: -50,
          radius: 200,
          fill: '#FCD34D',
          opacity: 0.3,
          locked: false,
        },
        {
          id: 'title-5',
          type: 'text',
          x: 80,
          y: 80,
          text: 'SPRING INTO',
          fontSize: 36,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#78350F',
          locked: false,
        },
        {
          id: 'title-5-2',
          type: 'text',
          x: 80,
          y: 130,
          text: 'YOUR NEW HOME',
          fontSize: 52,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#92400E',
          locked: false,
        },
        {
          id: 'promo-box',
          type: 'rectangle',
          x: 80,
          y: 220,
          width: 300,
          height: 80,
          fill: '#FFFFFF',
          locked: false,
        },
        {
          id: 'promo-text',
          type: 'text',
          x: 100,
          y: 245,
          text: 'Special Financing',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#92400E',
          locked: false,
        },
        {
          id: 'body-5',
          type: 'text',
          x: 80,
          y: 450,
          text: 'Contact us today for pre-approval!',
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#78350F',
          locked: false,
        },
      ],
    },
  },
  {
    id: 'luxury-modern',
    name: 'Luxury Property Showcase',
    category: 'Real Estate',
    size: '6x11',
    thumbnail: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop',
    design_data: {
      elements: [
        {
          id: 'bg-6',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 1100,
          height: 600,
          fill: '#000000',
          locked: true,
        },
        {
          id: 'gold-line-1',
          type: 'rectangle',
          x: 0,
          y: 0,
          width: 1100,
          height: 4,
          fill: '#D4AF37',
          locked: false,
        },
        {
          id: 'gold-line-2',
          type: 'rectangle',
          x: 0,
          y: 596,
          width: 1100,
          height: 4,
          fill: '#D4AF37',
          locked: false,
        },
        {
          id: 'title-6',
          type: 'text',
          x: 80,
          y: 60,
          text: 'EXCLUSIVE LISTING',
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: '300',
          fill: '#D4AF37',
          letterSpacing: 3,
          locked: false,
        },
        {
          id: 'headline-6',
          type: 'text',
          x: 80,
          y: 120,
          text: 'Waterfront Estate',
          fontSize: 56,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#FFFFFF',
          locked: false,
        },
        {
          id: 'price-6',
          type: 'text',
          x: 80,
          y: 200,
          text: '$2,495,000',
          fontSize: 48,
          fontFamily: 'Inter',
          fontWeight: 'bold',
          fill: '#D4AF37',
          locked: false,
        },
        {
          id: 'features-6',
          type: 'text',
          x: 80,
          y: 480,
          text: '5 Bed | 4.5 Bath | 4,200 Sq Ft | Private Dock',
          fontSize: 18,
          fontFamily: 'Inter',
          fill: '#E5E7EB',
          locked: false,
        },
      ],
    },
  },
];

export const templateCategories = ['All', 'Real Estate', 'Seasonal', 'Blank'];